name: Gold Drawings Processing Using Nautilus Librarian

on:
  pull_request:
    branches: [ main, issue-* ]
  workflow_dispatch:

jobs:
  process-gold-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.
          submodules: 'true'

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'

      - name: Install Librarian dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libvips-dev 

      - name: Install Librarian using Python package (documented way)
        run: pip install nautilus-librarian

      - name: Import GPG key used for testing
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.TEST_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TEST_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Run librarian gold image processing command
        run: |
          nautilus-librarian gold-images-processing --previous-ref HEAD~1  --current-ref HEAD
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
